In [1]:
import numpy as np
inp = np.matrix([[0.0], [1.0], [1.0]])

In [2]:
inp

matrix([[0.],
        [1.],
        [1.]])

In [3]:
w1 = np.matrix([[0.7, 0.2, 0.7], [0.8, 0.3, 0.6]], dtype=float)

In [4]:
w2 = np.matrix([[0.2, 0.4]], dtype=float)

In [5]:
y = 1

In [6]:
import math

def sigmoid_x(x):
    return 1 / (1 + math.pow(math.e, -x))

def sigmoid_mat(mat):
    for i in range(len(mat)):
        for j in range(len(mat[i])):
            mat[i][j] = sigmoid_x(mat[i][j])
    return mat
                
def sigmoid_prime_x(x):
    return sigmoid_x(x) * (1 - sigmoid_x(x))

def sigmoid_prime_mat(mat):
    for i in range(len(mat)):
        for j in range(len(mat[i])):
            mat[i][j] = sigmoid_prime_x(mat[i][j])
    return mat

In [7]:
def max_x(x):
    return max(x, 0)

def max_mat(mat):
    for i in range(len(mat)):
        for j in range(len(mat[i])):
            mat[i][j] = max_x(mat[i][j])
    return mat
                
def max_prime_x(x):
    return 1 if x > 0 else 0

def max_prime_mat(mat):
    for i in range(len(mat)):
        for j in range(len(mat[i])):
            mat[i][j] = max_prime_x(mat[i][j])
    return mat

In [8]:
def sigmoid_neiron(inp, w):
    z = w * inp
    
    a = z.copy()
    a = sigmoid_mat(a)
            
    return z, a

def max_neiron(inp, w):
    z = w * inp
    
    a = z.copy()
    a[0][0] = max_x(a[0][0])
    a[1][0] = sigmoid_x(a[1][0])
            
    return z, a

In [9]:
def from_input_to_output(inp, w1, w2):
    z1, a1 = max_neiron(inp, w1)
    z2, a2 = sigmoid_neiron(a1, w2)
    return z1, a1, z2, a2

In [10]:
z1, a1, z2, a2 = from_input_to_output(inp, w1, w2)

In [11]:
a1

matrix([[0.9      ],
        [0.7109495]])

In [31]:
def delta_out(y_hat, y, z):
    return (y_hat - y) * sigmoid_prime_mat(z)

def delta(w, delta_before, z):
    return (w.T * delta_before) * sigmoid_prime_mat(z)

In [13]:
delta_output = delta_out(a2[0][0], y, z2) 

In [14]:
delta_output

matrix([[-0.09146642]])

In [33]:
delta_hidden = delta(w2, delta_output, z1.T)

TypeError: only size-1 arrays can be converted to Python scalars

In [16]:
delta_hidden

matrix([[-0.0045097],
        [-0.0090194]])

In [17]:
w1

matrix([[0.7, 0.2, 0.7],
        [0.8, 0.3, 0.6]])

In [18]:
w213 = inp[2][0] * delta_hidden[0][0]

In [19]:
w223 = inp[2][0] * delta_hidden[1][0]

In [20]:
w213[0][0]

matrix([[-0.0045097]])

In [21]:
w223[0][0]

matrix([[-0.0090194]])

In [24]:
z2

matrix([[0.24652227]])

In [25]:
z1.T

matrix([[0.9, 0.9]])