<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#2.1.-Numpy-ndarray---создание" data-toc-modified-id="2.1.-Numpy-ndarray---создание-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>2.1. Numpy ndarray - создание</a></span></li><li><span><a href="#2.2.-Numpy-ndarray---индексы" data-toc-modified-id="2.2.-Numpy-ndarray---индексы-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>2.2. Numpy ndarray - индексы</a></span><ul class="toc-item"><li><span><a href="#TLDR:" data-toc-modified-id="TLDR:-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>TLDR:</a></span></li></ul></li><li><span><a href="#2.3.-Numpy-ndarray---элементарные-операции-с-массивами" data-toc-modified-id="2.3.-Numpy-ndarray---элементарные-операции-с-массивами-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>2.3. Numpy ndarray - элементарные операции с массивами</a></span><ul class="toc-item"><li><span><a href="#TLDR:" data-toc-modified-id="TLDR:-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>TLDR:</a></span></li></ul></li><li><span><a href="#2.4.-Numpy---основные-функции." data-toc-modified-id="2.4.-Numpy---основные-функции.-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>2.4. Numpy - основные функции.</a></span><ul class="toc-item"><li><span><a href="#TLDR:" data-toc-modified-id="TLDR:-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>TLDR:</a></span></li></ul></li><li><span><a href="#2.5.-Numpy---I/O." data-toc-modified-id="2.5.-Numpy---I/O.-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>2.5. Numpy - I/O.</a></span></li></ul></div>

In [17]:
%matplotlib inline
import matplotlib.pyplot as plt

# 2.1. Numpy ndarray - создание

Numpy - библиотека для векторизованных вычислений в Python'e. Написана на C. Основной объект в numpy - nddarray, который располагается напрерывно в памяти и позволяет производить быстрые вычисления.

In [18]:
import numpy as np

In [19]:
%%timeit
a = np.array(list(range(10000)))
a * a

1.11 ms ± 26 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [20]:
%%timeit
a = np.array(list(range(10000)))
a ** 2

948 µs ± 6.31 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [21]:
%%timeit
a = np.arange(10000)
a ** 2

13.2 µs ± 120 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Создание массива

In [22]:
a = np.array([1, 2, 3, 4])

In [23]:
a.shape

(4,)

Shape - кортеж, который указывает число элементов в каждом измерении. 

In [24]:
a = np.array([[1, 2], [3, 4]])

In [25]:
a

array([[1, 2],
       [3, 4]])

In [26]:
a.size

4

In [27]:
a.shape

(2, 2)

In [28]:
a.dtype

dtype('int32')

In [29]:
a.itemsize

4

In [30]:
a.nbytes

16

In [31]:
a.reshape(4, 1)

array([[1],
       [2],
       [3],
       [4]])

In [32]:
# a.reshape(1, 3)

In [33]:
a.reshape(4, -1)

array([[1],
       [2],
       [3],
       [4]])

In [34]:
a.reshape(1, -1).shape

(1, 4)

При желании, можно использовать np.size(np.object) и np.shape(np.object):

In [35]:
np.size(a)

4

In [36]:
np.shape(a)

(2, 2)

При необходимости, не стоит принебрегать встроенной справкой:

In [38]:
# np.array()

И специальными функциями numpy:

In [39]:
np.lookfor('create list')

Search results for 'create list'
--------------------------------
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mrecords.fromrecords
    Creates a MaskedRecords from a list of records.
numpy.core._dtype._construction_repr
    Creates a string repr of the dtype, excluding the 'dtype()' part
numpy.partition
    Return a partitioned copy of an array.
numpy.nested_iters
    Create nditers for use in nested loops
numpy.chararray.tolist
    a.tolist()
numpy.distutils.fcompiler.FCompiler._need_link
    Return true if we need to relink the files listed in 'objects'
numpy.distutils.fcompiler.FCompiler.create_static_lib
    Link a bunch of stuff together to create a static library file.
numpy.distutils.command.sdist.sdist.prune_file_list
    Prune off branches that might slip into the file list as created
numpy.distutils.misc_util.Configuration.add_extension
    Add extension to configuration.
numpy.distutils.intelccompiler.IntelCCompilerW.cre

и IPython:

In [40]:
np.sa*?

In [41]:
a

array([[1, 2],
       [3, 4]])

In [42]:
a[0, 0] = 100

In [43]:
a

array([[100,   2],
       [  3,   4]])

**Создание массивов**

Создавать из списков мы уже умеем:

In [44]:
x = [1, 2, 3, 4]

In [45]:
np.array([1, 2, 3, 4], dtype=np.int16)

array([1, 2, 3, 4], dtype=int16)

In [46]:
np.arange(100, 1000, 30)

array([100, 130, 160, 190, 220, 250, 280, 310, 340, 370, 400, 430, 460,
       490, 520, 550, 580, 610, 640, 670, 700, 730, 760, 790, 820, 850,
       880, 910, 940, 970])

In [47]:
np.linspace(0, 1, 25)

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

In [48]:
np.linspace(0, 1, 25, endpoint=False)

array([0.  , 0.04, 0.08, 0.12, 0.16, 0.2 , 0.24, 0.28, 0.32, 0.36, 0.4 ,
       0.44, 0.48, 0.52, 0.56, 0.6 , 0.64, 0.68, 0.72, 0.76, 0.8 , 0.84,
       0.88, 0.92, 0.96])

In [49]:
np.linspace(0, 1, 26)

array([0.  , 0.04, 0.08, 0.12, 0.16, 0.2 , 0.24, 0.28, 0.32, 0.36, 0.4 ,
       0.44, 0.48, 0.52, 0.56, 0.6 , 0.64, 0.68, 0.72, 0.76, 0.8 , 0.84,
       0.88, 0.92, 0.96, 1.  ])

In [50]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [51]:
np.ones(3)

array([1., 1., 1.])

In [52]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [53]:
np.ones((3, 2), 'complex')

array([[1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j]])

In [54]:
A = np.arange(100).reshape(-1, 25)

In [55]:
np.ones_like(A)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1]])

In [56]:
np.zeros_like(A)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0]])

In [57]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
np.diag(np.array([1, 2, 3, 4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

** Случайные массивы **

на интервале [0,1]:

In [59]:
np.random.rand(3, 2)

array([[0.50755507, 0.0211933 ],
       [0.43352176, 0.44631306],
       [0.23881999, 0.83024573]])

Нормально распределенные:

In [60]:
np.random.randn(3, 2)

array([[ 0.53942869,  1.52676162],
       [-3.2771929 , -1.84856065],
       [ 0.67212494, -1.49297925]])

-- N: иногда полезно получить случайное целое число:

In [61]:
np.random.randint(2, 10)

6

In [62]:
A = np.arange(5)
print(A)
A[[0, 1, -1]]

[0 1 2 3 4]


array([0, 1, 4])

# 2.2. Numpy ndarray - индексы

Отдельно рассмотрим 1-мерный и многомерные массивы.

In [63]:
t = np.random.rand(3,)

In [64]:
t

array([0.17998223, 0.30851712, 0.98898166])

Для одномерного массива получим сразу элемент, который находится по данному индексу. Для n-мерного массива подобная индексация вернет массив размера n-1.

In [65]:
t = np.random.rand(3, 5, 10)
t

array([[[0.92284354, 0.13187791, 0.98859553, 0.06957758, 0.05743923,
         0.86788253, 0.86384208, 0.75982357, 0.69535961, 0.48451152],
        [0.5606719 , 0.99110785, 0.08316527, 0.7651928 , 0.31064629,
         0.77118149, 0.26657616, 0.36545819, 0.05168242, 0.01191449],
        [0.94236298, 0.94955498, 0.96673269, 0.43919941, 0.16558616,
         0.98572534, 0.77168362, 0.84186144, 0.30150026, 0.95039966],
        [0.78334247, 0.37160832, 0.26094864, 0.43986415, 0.43577525,
         0.59148367, 0.73159736, 0.06025293, 0.36019888, 0.21079724],
        [0.4639624 , 0.9009038 , 0.29132058, 0.8034707 , 0.41006053,
         0.56073403, 0.30433214, 0.35091211, 0.919799  , 0.18521465]],

       [[0.29687116, 0.0145046 , 0.57172792, 0.69007176, 0.71862751,
         0.44053735, 0.48332068, 0.43486523, 0.16241445, 0.69339443],
        [0.04214998, 0.66037428, 0.429656  , 0.2952285 , 0.19949365,
         0.30985193, 0.53775309, 0.63107826, 0.35891014, 0.80593306],
        [0.20637426, 0.82

In [66]:
t.shape

(3, 5, 10)

In [67]:
t[0, 1, :]

array([0.5606719 , 0.99110785, 0.08316527, 0.7651928 , 0.31064629,
       0.77118149, 0.26657616, 0.36545819, 0.05168242, 0.01191449])

In [68]:
np.random.rand(3, 5, 10)[1].shape

(5, 10)

In [69]:
np.random.rand(3, 5)[1].shape

(5,)

Можно использовать ':' вместо индекса:

In [70]:
A = np.random.rand(3, 5)

In [71]:
A

array([[0.89879403, 0.30473973, 0.70977855, 0.36944788, 0.640552  ],
       [0.8765493 , 0.40220108, 0.36308586, 0.15075893, 0.82333883],
       [0.0214264 , 0.51240288, 0.88909563, 0.64204477, 0.96863461]])

In [72]:
A[0, :]

array([0.89879403, 0.30473973, 0.70977855, 0.36944788, 0.640552  ])

In [73]:
A[:, 0]

array([0.89879403, 0.8765493 , 0.0214264 ])

Поддерживается стандартный протокол - python slicing syntax ([lower:upper:step]) :

In [74]:
A[0, :]

array([0.89879403, 0.30473973, 0.70977855, 0.36944788, 0.640552  ])

In [75]:
A[0, :][0:4:2]

array([0.89879403, 0.70977855])

In [76]:
a = A[0, :]

In [77]:
a

array([0.89879403, 0.30473973, 0.70977855, 0.36944788, 0.640552  ])

Операция slicing создает т.н. view - то есть данные не копируются, поэтому исходный объект по адресу - mutable.

In [78]:
A[0,:][0:4:2]

array([0.89879403, 0.70977855])

In [79]:
A[0,:][0:4:2] = [1.0, 2.5]

In [80]:
A

array([[1.        , 0.30473973, 2.5       , 0.36944788, 0.640552  ],
       [0.8765493 , 0.40220108, 0.36308586, 0.15075893, 0.82333883],
       [0.0214264 , 0.51240288, 0.88909563, 0.64204477, 0.96863461]])

Параметры для slicing могут пропускаться:

In [81]:
A[0, :][0:4:2]

array([1. , 2.5])

In [82]:
A[0, :][0:4]

array([1.        , 0.30473973, 2.5       , 0.36944788])

In [83]:
A[0, :][:3]

array([1.        , 0.30473973, 2.5       ])

In [84]:
A[0, :][3:]

array([0.36944788, 0.640552  ])

In [85]:
A[0, :]

array([1.        , 0.30473973, 2.5       , 0.36944788, 0.640552  ])

In [86]:
A[0, :][::-1]

array([0.640552  , 0.36944788, 2.5       , 0.30473973, 1.        ])

In [87]:
A[0, :]

array([1.        , 0.30473973, 2.5       , 0.36944788, 0.640552  ])

In [88]:
A[0, :][:-3]

array([1.        , 0.30473973])

In [89]:
A[0, :][-3:]

array([2.5       , 0.36944788, 0.640552  ])

** Fancy Indexing **

Этим термином обозначается индексирование с помощью массивов (или иных итерируемых конструкций).

In [90]:
A

array([[1.        , 0.30473973, 2.5       , 0.36944788, 0.640552  ],
       [0.8765493 , 0.40220108, 0.36308586, 0.15075893, 0.82333883],
       [0.0214264 , 0.51240288, 0.88909563, 0.64204477, 0.96863461]])

In [91]:
row_indices = [1, 2]
A[row_indices]

array([[0.8765493 , 0.40220108, 0.36308586, 0.15075893, 0.82333883],
       [0.0214264 , 0.51240288, 0.88909563, 0.64204477, 0.96863461]])

In [92]:
col_indices = [1, -1]
A[row_indices, col_indices]

array([0.40220108, 0.96863461])

Возможно Булево индексирование (**Boolean indexing**):

In [93]:
B = np.array([n for n in range(5)])
row_mask = np.array([True, False, True, False, False])
B[row_mask]

array([0, 2])

In [94]:
B[B > 2]

array([3, 4])

In [95]:
row_mask = np.array([1, 0, 1, 0, 0], dtype=bool)
B[row_mask]

array([0, 2])

Это очень удобно, как вы наверняка догадались, если мы хотим отобрать данные, отвечающие определенным условиям:

In [96]:
x = np.arange(0, 10, 0.5)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [97]:
mask = (5 < x) * (x < 7.5)
mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [98]:
mask = (5 < x) & (x < 7.5)
mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [99]:
x[mask]

array([5.5, 6. , 6.5, 7. ])

In [100]:
a = np.array([[1, 2], [3, 4]])

In [101]:
a * (a > 1)

array([[0, 2],
       [3, 4]])

In [102]:
a[a > 0]

array([1, 2, 3, 4])

Получить список индексов элементов, отвечающих заданной маске, можно с помощью **where**:

In [103]:
indices = np.where(mask)

indices

(array([11, 12, 13, 14], dtype=int64),)

In [104]:
x[indices]

array([5.5, 6. , 6.5, 7. ])

**take** еще одна конструкция выбора элементов массива:

In [105]:
v = np.arange(-3, 3)
row_indices = [1, 3, 5]

In [106]:
v

array([-3, -2, -1,  0,  1,  2])

In [107]:
v[row_indices]

array([-2,  0,  2])

In [108]:
v.take(row_indices)

array([-2,  0,  2])

In [109]:
np.take(v, row_indices)

array([-2,  0,  2])

## TLDR:
* для доступа к элементам массива пользуйтесь slicing и помните, что slicing создает view, а значит исходный массив может быть изменен.

# 2.3. Numpy ndarray - элементарные операции с массивами

** Broadcasting **

Концепеция broadcasting является ключевой для понимания операций с массивами. Обычно, операции с массивами производятся поэлементно. 

In [110]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])

In [111]:
a / b

array([0.5, 1. , 1.5])

Что, если массивы разного размера? Начнем с простого - скаляр и вектор:

In [112]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

Все просто - скаляр словно "вырастает" (broadcasted) до размеров вектора и производится поэлементная операция (разумеется, это умозрительная аналогия - новый вектор из 2 не создается!).

Общее правило таково:

операция может произведена если размерность "крайних" осей массивов совпадает (trailing dimension), либо один из элементов является скаляром.

Пример из оффициальной документации:

In [113]:
'''

Image  (3d array): 256 x 256 x 3
Scale  (1d array):             3
Result (3d array): 256 x 256 x 3

A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5

'''
pass

In [114]:
a = np.random.randint(0, 5, (8, 1, 6, 1))

In [115]:
b = np.random.randint(0, 5, (7, 1, 5))

In [116]:
a[:1]

array([[[[1],
         [1],
         [3],
         [0],
         [4],
         [1]]]])

In [117]:
b[:1]

array([[[4, 3, 2, 1, 0]]])

In [118]:
a[:1] * b[:1]

array([[[[ 4,  3,  2,  1,  0],
         [ 4,  3,  2,  1,  0],
         [12,  9,  6,  3,  0],
         [ 0,  0,  0,  0,  0],
         [16, 12,  8,  4,  0],
         [ 4,  3,  2,  1,  0]]]])

In [119]:
(a * b).shape

(8, 7, 6, 5)

а вот эти операции дадут вам ошибку:

In [120]:
'''
A      (1d array):  3
B      (1d array):  4 # trailing dimensions do not match

A      (2d array):      2 x 1
B      (3d array):  8 x 4 x 3 # second from last dimensions mismatched
'''
pass

In [122]:
# x = np.arange(4)
# xx = x.reshape(4, 1)
# y = np.ones(5)
# z = np.ones((3, 4))

# print(x.shape)

# print(y.shape)

# x + y

In [123]:
y

array([1., 1., 1., 1., 1.])

In [124]:
print(xx.shape)
print(y.shape)
print((xx + y).shape)
print(xx + y)

print('-------')

print(x.shape)
print(z.shape)
print((x + z).shape)
print(x + z)

(4, 1)
(5,)
(4, 5)
[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]
-------
(4,)
(3, 4)
(3, 4)
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


Классный пример из официальной документации:

In [125]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [126]:
a[:, np.newaxis]

array([[ 0.],
       [10.],
       [20.],
       [30.]])

In [127]:
a[:, np.newaxis].shape

(4, 1)

** Операции вида "массив - скаляр" **

In [128]:
A

array([[1.        , 0.30473973, 2.5       , 0.36944788, 0.640552  ],
       [0.8765493 , 0.40220108, 0.36308586, 0.15075893, 0.82333883],
       [0.0214264 , 0.51240288, 0.88909563, 0.64204477, 0.96863461]])

In [129]:
A + 2

array([[3.        , 2.30473973, 4.5       , 2.36944788, 2.640552  ],
       [2.8765493 , 2.40220108, 2.36308586, 2.15075893, 2.82333883],
       [2.0214264 , 2.51240288, 2.88909563, 2.64204477, 2.96863461]])

** Операции вида "массив - массив" **

Производятся поэлементно с учетом правил broadcasting:

In [130]:
A * A

array([[1.00000000e+00, 9.28663054e-02, 6.25000000e+00, 1.36491733e-01,
        4.10306870e-01],
       [7.68338667e-01, 1.61765710e-01, 1.31831340e-01, 2.27282563e-02,
        6.77886836e-01],
       [4.59090621e-04, 2.62556708e-01, 7.90491037e-01, 4.12221484e-01,
        9.38253017e-01]])

In [131]:
A / A

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

** Матричные операции**

In [132]:
A = np.random.rand(3,3)

In [133]:
np.dot(A, A)

array([[2.09798336, 1.15001593, 1.43429773],
       [1.70596837, 1.0878828 , 1.19863957],
       [1.92428042, 1.13422295, 1.34229159]])

In [134]:
v = np.random.randn(3)

In [135]:
v

array([ 1.79241222, -0.44577796,  0.14732117])

In [136]:
v[:, np.newaxis]

array([[ 1.79241222],
       [-0.44577796],
       [ 0.14732117]])

In [137]:
A * v

array([[ 1.53998307, -0.31531173,  0.10089711],
       [ 1.74855547, -0.11480114,  0.09288343],
       [ 1.75292793, -0.23441214,  0.08602357]])

In [138]:
np.dot(A, v)

array([1.32556845, 1.72663777, 1.60453937])

In [139]:
np.dot(A, v[:, np.newaxis])

array([[1.32556845],
       [1.72663777],
       [1.60453937]])

In [140]:
np.dot(v[np.newaxis, :], A)

array([[1.2491883 , 1.23049298, 1.03255305]])

In [141]:
np.dot(v, v)

3.433163079185935

Если хочется использовать по умолчанию операции из матричной алгебры, то можно использовать конструктор matrix().

In [142]:
M = np.matrix(A)

In [143]:
v1 = np.matrix(v).T

In [144]:
M.shape

(3, 3)

In [145]:
v1.shape

(3, 1)

In [146]:
v1.T * v1

matrix([[3.43316308]])

In [147]:
M * v1

matrix([[1.32556845],
        [1.72663777],
        [1.60453937]])

** Преобразование массивов**

In [148]:
A.T

array([[0.85916791, 0.975532  , 0.97797143],
       [0.70732911, 0.25752986, 0.52584954],
       [0.68487858, 0.6304826 , 0.58391859]])

** reshape **

In [149]:
a

array([ 0., 10., 20., 30.])

In [150]:
a = a.reshape((2, 2))

In [151]:
a.reshape(2, -1)

array([[ 0., 10.],
       [20., 30.]])

** resize **

In [152]:
a = np.arange(4)

In [153]:
a.resize((8,))

In [154]:
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [155]:
a = np.array([[1, 2], [3, 4]])
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [156]:
np.tile(a, 3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

** concatenate **

In [157]:
a

array([[1, 2],
       [3, 4]])

In [158]:
b = np.array([[5, 6]])

In [159]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [160]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

** hstack **

Название говорит само за себя - horizontal stack.

In [161]:
np.hstack((a, b.T))

array([[1, 2, 5],
       [3, 4, 6]])

In [162]:
a.shape

(2, 2)

In [163]:
b.T.shape

(2, 1)

** vstack **

In [164]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [165]:
a.shape

(2, 2)

In [166]:
b.shape

(1, 2)

** Копии и view **

Мы помним, что очень важно различать копирование объекта и присваивание новой ссылки на объект. Numpy в этом смысле не отличается от списков:

In [167]:
A = np.array([[1, 2], [3, 4]])

In [168]:
B = A

In [169]:
B[0, 0] = 10

In [170]:
A

array([[10,  2],
       [ 3,  4]])

Если это не тот тип поведения, который нам нужен - следует использовать np.copy():

In [171]:
A = np.array([[1, 2], [3, 4]])

In [172]:
B = np.copy(A)

In [173]:
B[0, 0] = 100

In [174]:
A

array([[1, 2],
       [3, 4]])

Важно помнить, что если вы используете view массива, то копии вы не создаете!

In [175]:
a = np.arange(10)

In [176]:
b = a[::2]

In [177]:
np.may_share_memory(a, b)

True

In [178]:
c = a[::2].copy()
np.may_share_memory(a, c)

False

In [179]:
d = a.T
np.may_share_memory(a, d)

True

In [180]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [181]:
b[0] = -11

In [182]:
a

array([-11,   1,   2,   3,   4,   5,   6,   7,   8,   9])

## TLDR:
* следует отличать копию массива и view;
* при осуществлении операций помните про правила broadcasting;
* запомните hstack и vstack.

# 2.4. Numpy - основные функции.

** Встроенные функции массива **

In [183]:
m = np.random.randint(0, 10, (3, 3))

In [184]:
m

array([[5, 7, 8],
       [4, 7, 6],
       [7, 7, 2]])

In [185]:
m.sum()

53

In [186]:
m.max()

8

** Всегда используйте встроенные функции! **

In [187]:
a = np.random.rand(100000)

In [188]:
%timeit -n 1000 max(a)

8.42 ms ± 404 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [189]:
%timeit -n 1000 a.max()

22 µs ± 2.87 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [190]:
%timeit -n 1000 sum(a)

11.1 ms ± 853 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [191]:
%timeit -n 1000 a.sum()

39.1 µs ± 4.74 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Просто считать сумму элементов матрицы или находить максимальный элемент не так интересно, и тут нам помогают axis:

In [192]:
m

array([[5, 7, 8],
       [4, 7, 6],
       [7, 7, 2]])

In [193]:
m.sum(axis=0)

array([16, 21, 16])

In [194]:
m.sum(axis=1)

array([20, 17, 16])

In [195]:
m.max(axis=0)

array([7, 7, 8])

Очень полезно произведение всех элементов:

In [196]:
m.prod(axis=1)

array([280, 168,  98])

Кумулятивная сумма элементов:

In [197]:
m.cumsum()

array([ 5, 12, 20, 24, 31, 37, 44, 51, 53], dtype=int32)

Кумулятивное произведение:

In [198]:
m.cumprod()

array([      5,      35,     280,    1120,    7840,   47040,  329280,
       2304960, 4609920], dtype=int32)

**Простые статистики**

**Среднее**

In [199]:
m.mean(axis=0)

array([5.33333333, 7.        , 5.33333333])

In [200]:
np.mean(m, axis=0)

array([5.33333333, 7.        , 5.33333333])

In [201]:
np.mean(a)

0.5000830497618594

In [202]:
a.mean()

0.5000830497618594

**Медиана**

In [203]:
np.median(m, axis=0)

array([5., 7., 6.])

In [204]:
np.median(a)

0.4996562080856033

** Дисперсия **

In [205]:
np.std(m, axis=0)

array([1.24721913, 0.        , 2.49443826])

In [206]:
m.std(axis=0)

array([1.24721913, 0.        , 2.49443826])

In [207]:
np.var(a)

0.08331399594146519

In [208]:
a.var()

0.08331399594146519

** Сортировка **

In [209]:
np.sort(a)

array([2.80374084e-06, 2.59103536e-05, 4.30852707e-05, ...,
       9.99993295e-01, 9.99996412e-01, 9.99999120e-01])

Функция выше возвращает отсортированную копию массива. Если нужна сортировка in-place:

In [210]:
a.sort()

In [211]:
a = np.random.rand(100000)

Также иногда бывает полезно получить только список индексов в правильном порядке:

In [212]:
np.argsort(a)

array([83640, 76700, 81598, ..., 38049,  4624,  3884], dtype=int64)

In [213]:
np.argmax(a)

3884

In [214]:
np.argmin(a)

83640

In [215]:
np.nonzero(a)

(array([    0,     1,     2, ..., 99997, 99998, 99999], dtype=int64),)

** Функции для работы с матрицами **

In [216]:
m

array([[5, 7, 8],
       [4, 7, 6],
       [7, 7, 2]])

In [217]:
np.diag(m)

array([5, 7, 2])

In [218]:
m.diagonal()

array([5, 7, 2])

Для целого класса функций из линейной алгебры есть свой суб-модуль np.linalg.

http://docs.scipy.org/doc/numpy/reference/routines.linalg.html

In [219]:
MM = np.random.randn(9, 6)

In [220]:
U, s, V = np.linalg.svd(MM, full_matrices=False)
U.shape, V.shape, s.shape

((9, 6), (6, 6), (6,))

In [221]:
s

array([3.86685687, 3.39630386, 2.21713048, 1.49549894, 1.01376816,
       0.74689707])

In [222]:
S = np.diag(s)
np.allclose(MM, np.dot(U, np.dot(S, V)))

True

** Векторизация кода **

В numpy есть встроенная функция vectorize, которая "автоматически" векторизует вашу функцию:

In [223]:
def heavyside(x):
    if x >= 0:
        return 1
    else:
        return 0

In [224]:
heavyside(np.array([-3, -2, -1, 0, 1, 2, 3]))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
heavyside_vec = np.vectorize(heavyside)

In [ ]:
heavyside_vec(np.array([-3, -2, -1, 0, 1, 2, 3]))

Тем не менее, лучше сразу пишите так:

In [ ]:
def heavyside(x):
    return 1 * (x >= 0)

In [ ]:
heavyside(np.array([-3,-2,-1,0,1,2,3]))

In [ ]:
np.array([-3,-2,-1,0,1,2,3]) >= 0

In [ ]:
1 * (np.array([-3,-2,-1,0,1,2,3]) >= 0)

** Условные выражения **

Как вы уже поняли, для вектора конструкция типа if (vector) не подходит.

In [ ]:
M

In [ ]:
if (M > 5).any():
    print("at least one element in M is larger than 5")
else:
    print("no element in M is larger than 5")

In [ ]:
if (M > 5).all():
    print("all elements in M are larger than 5")
else:
    print("all elements in M are not larger than 5")

## TLDR:
- всегда используйте встроенные в np функции;
- векторизуйте везде, где это возможно!

# 2.5. Numpy - I/O.

В данном случае у нас на выбор 2 опции - либо формат numpy, либо просто текстовый файл.

In [ ]:
!ls

In [ ]:
np.save("random.npy", M)

In [ ]:
!ls

In [ ]:
!cat Black_man.txt | head -9

In [ ]:
np.load("random.npy")

In [ ]:
np.savetxt('random.csv', M, delimiter='\t')

In [ ]:
! cat random.csv

In [ ]:
np.loadtxt('random.csv')

# А теперь задачки!

In [ ]:
(lambda x: x + 1)(np.arange(100))

In [ ]:
lambda x, y: x + y

In [ ]:
lambda x, y: x * y

In [ ]:
_(1, 2)

#### Написать функцию, которая поможет развернуть все слова в строке:

In [ ]:
def reverser(string):
    return 

#### Написать функцию, которая определяет является ли число палиндромом

In [ ]:
def is_palindrom(string):
    return 

In [ ]:
is_palindrom("дед")

#### Сложите цифры целого числа

In [ ]:
a = 126567654

#### Извлеките из массива числа, делимые на 15.

In [ ]:
nums = np.array([45, 55, 60, 37, 100, 105, 220])

#### Напишите программу, которая принимает текст и выводит два слова: наиболее часто встречающееся и самое длинное.

In [ ]:
with open('./Black_man.txt') as f:
    black = f.readlines()

In [ ]:
lower = (" ".join(black).lower())

In [ ]:
only_letters = ""
for i in lower:
    if (i >= "а" and i <= "я") or i in [" ", "\n"]:
        only_letters += i

#### Напишите функцию, которая создаёт комбинацию двух списков таким образом:

[1, 2, 3] (+) [11, 22, 33] -> [1, 11, 2, 22, 3, 33]

In [ ]:
x = [1, 2, 3]
y = [11, 22, 33, 1123]

In [ ]:
x, y = np.random.randint(1, 10, 10000), np.random.randint(1, 10, 10000)

In [ ]:
%timeit merge(x, y)

In [ ]:
%timeit merge_optimal(x, y)

In [ ]:
merge(x, y) == merge_optimal(x, y)

#### Написать функцию, которая удаляет лишние пробелы в строке

In [ ]:
def delete_spaces(string):
    return

In [ ]:
%timeit delete_spaces_optimal(lower)

In [ ]:
%timeit delete_spaces(lower)