In [1]:
%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
import numpy as np

In [4]:
%%timeit
a = np.array(list(range(1000)))
a * a

98.9 µs ± 3.4 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [5]:
%%timeit
a = np.arange(1000)
a * a

3.74 µs ± 251 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
a = np.array([1, 2, 3, 4])

In [8]:
a.shape              # Число элементов в измерении

(4,)

In [9]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [10]:
a.size

4

In [11]:
a.shape

(2, 2)

In [12]:
a.dtype

dtype('int32')

In [13]:
a.itemsize

4

In [14]:
a.nbytes

16

In [15]:
a.reshape(4, 1)           # преобразование матрицы

array([[1],
       [2],
       [3],
       [4]])

In [16]:
a.reshape(1, -1)          # автоматическое подставление второй размерности

array([[1, 2, 3, 4]])

In [17]:
a.reshape(1, -1).shape

(1, 4)

In [19]:
np.size(a)                # те же методы от np

4

In [ ]:
np.array               

**Shift + tab** - документация. Чем больше taб, тем больше документации

**np.lookfor('create array')** - поиск функции по ключевым словам

**np.sa*?** - найти функцию по началу

In [20]:
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.lib.Arrayterator
    Buffered iterator for big arrays.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mvoid.__new__
    Create a new masked array from scratch.
numpy.ma.MaskedArray.__new__
    Create a new masked array from scratch.
nu

In [21]:
np.sa*?

### Создание массива

In [22]:
np.array([1, 2, 3, 4], dtype=np.int16)

array([1, 2, 3, 4], dtype=int16)

In [23]:
np.arange(1, 10, 1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.linspace(0, 1, 25, endpoint=False)           # разбить отрезок от start до stop на n частей, end - вкючать ли правую границу

array([0.  , 0.04, 0.08, 0.12, 0.16, 0.2 , 0.24, 0.28, 0.32, 0.36, 0.4 ,
       0.44, 0.48, 0.52, 0.56, 0.6 , 0.64, 0.68, 0.72, 0.76, 0.8 , 0.84,
       0.88, 0.92, 0.96])

In [25]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [27]:
np.ones(3, 'complex')

array([1.+0.j, 1.+0.j, 1.+0.j])

In [26]:
np.zeros(2)

array([0., 0.])

In [31]:
A = np.arange(100).reshape(-1, 25)
np.ones_like(A)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1]])

In [32]:
np.zeros_like(A)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0]])

In [36]:
np.eye(10, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
np.diag(np.array([1, 2, 3, 4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### Генерация случайных массивов

In [38]:
np.random.rand(3, 2)

array([[0.50755507, 0.0211933 ],
       [0.43352176, 0.44631306],
       [0.23881999, 0.83024573]])

In [39]:
np.random.randn(3, 2)

array([[ 0.53942869,  1.52676162],
       [-3.2771929 , -1.84856065],
       [ 0.67212494, -1.49297925]])

In [41]:
np.random.randint(0, 10, (2, 3))          # матрица 2х3 с числами от 0 до 10

array([[0, 5, 9],
       [2, 1, 3]])

In [42]:
t = np.random.rand(3, 5, 10)
t

array([[[0.59763234, 0.42286597, 0.93348609, 0.99397099, 0.54783884,
         0.73023457, 0.02798429, 0.86359128, 0.99863076, 0.32530982],
        [0.85026083, 0.61149212, 0.44111308, 0.52720459, 0.77982061,
         0.25135019, 0.46289232, 0.84718667, 0.67802359, 0.36786229],
        [0.13798301, 0.40280945, 0.93129709, 0.67316279, 0.41922982,
         0.56866661, 0.04171068, 0.99563413, 0.61900422, 0.77946612],
        [0.93133864, 0.34161856, 0.8112992 , 0.8727098 , 0.66598823,
         0.58878655, 0.89335226, 0.44858402, 0.24438358, 0.81417296],
        [0.6971494 , 0.40960454, 0.00571508, 0.95401436, 0.6052526 ,
         0.00654628, 0.49849349, 0.59863535, 0.30014745, 0.4617575 ]],

       [[0.49559978, 0.58565914, 0.86963799, 0.83222696, 0.77856305,
         0.54843311, 0.61345196, 0.73426973, 0.56636909, 0.77521013],
        [0.98654561, 0.78920569, 0.61433598, 0.15828454, 0.47638631,
         0.28364917, 0.15381227, 0.77722042, 0.05896313, 0.0791225 ],
        [0.66423846, 0.52

### Индексы

In [43]:
t[0, :]           # нулевая размерность, все обьекты

array([[0.59763234, 0.42286597, 0.93348609, 0.99397099, 0.54783884,
        0.73023457, 0.02798429, 0.86359128, 0.99863076, 0.32530982],
       [0.85026083, 0.61149212, 0.44111308, 0.52720459, 0.77982061,
        0.25135019, 0.46289232, 0.84718667, 0.67802359, 0.36786229],
       [0.13798301, 0.40280945, 0.93129709, 0.67316279, 0.41922982,
        0.56866661, 0.04171068, 0.99563413, 0.61900422, 0.77946612],
       [0.93133864, 0.34161856, 0.8112992 , 0.8727098 , 0.66598823,
        0.58878655, 0.89335226, 0.44858402, 0.24438358, 0.81417296],
       [0.6971494 , 0.40960454, 0.00571508, 0.95401436, 0.6052526 ,
        0.00654628, 0.49849349, 0.59863535, 0.30014745, 0.4617575 ]])

In [44]:
t[0, 1, :]

array([0.85026083, 0.61149212, 0.44111308, 0.52720459, 0.77982061,
       0.25135019, 0.46289232, 0.84718667, 0.67802359, 0.36786229])

In [45]:
t[0, 1, 5]

0.25135019341230314

Можно использовать : вместо индекса

In [46]:
A = np.random.rand(3, 5)

In [47]:
A

array([[0.43352092, 0.17829589, 0.75216225, 0.05047057, 0.08266852],
       [0.03858344, 0.46527861, 0.60382866, 0.18178934, 0.5190297 ],
       [0.71015328, 0.92498038, 0.52913164, 0.97118573, 0.54725276]])

In [48]:
A[0, :]

array([0.43352092, 0.17829589, 0.75216225, 0.05047057, 0.08266852])

In [49]:
A[:, 0]

array([0.43352092, 0.03858344, 0.71015328])

In [50]:
A[0, :][0:4:1]          # первые 4 значения первой строки

array([0.43352092, 0.17829589, 0.75216225, 0.05047057])

In [51]:
a = A[0, :]             # нихрена не копия, меняться будут вместе

In [52]:
a

array([0.43352092, 0.17829589, 0.75216225, 0.05047057, 0.08266852])

In [53]:
A[0, :][::-1]           # развернуть массив

array([0.08266852, 0.05047057, 0.75216225, 0.17829589, 0.43352092])

In [54]:
A[0, :][::-3]

array([0.08266852, 0.17829589])

In [56]:
x = np.arange(0, 10, 0.5)

In [57]:
mask = (5 < x)

In [58]:
mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [59]:
x[mask]

array([5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [62]:
x * (x > 1)

array([0. , 0. , 0. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [64]:
x[x > 0].shape

(19,)

In [66]:
indices = np.where(mask)

In [67]:
indices

(array([11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int64),)

In [68]:
x[indices]

array([5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

**take** еще одна конструкция выборта элементов массива

### Элементарные операции с массивами

In [69]:
a = np.array([1, 2, 3])
b = np.array([2, 2, 3])

In [70]:
a / b                            # должны быть одинакогого размера или один из массивов является скаляром

array([0.5, 1. , 1. ])

In [71]:
a = np.array([1, 2, 3])
b = 2
a * b

array([2, 4, 6])

In [75]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis] + b                        # создать новую размерность

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [76]:
a + 2

array([ 2., 12., 22., 32.])

In [77]:
np.dot(a, a)

1400.0

In [78]:
a

array([ 0., 10., 20., 30.])

In [79]:
a.T

array([ 0., 10., 20., 30.])

In [81]:
a = a.reshape((2, 2))

In [82]:
a

array([[ 0., 10.],
       [20., 30.]])

In [83]:
a.T

array([[ 0., 20.],
       [10., 30.]])

In [84]:
np.repeat(a, 2)             # продублировать элементы

array([ 0.,  0., 10., 10., 20., 20., 30., 30.])

In [85]:
np.tile(a, 2)

array([[ 0., 10.,  0., 10.],
       [20., 30., 20., 30.]])

In [89]:
b = a.reshape((2, 2))
b

array([[ 0., 10.],
       [20., 30.]])

In [90]:
a

array([[ 0., 10.],
       [20., 30.]])

In [94]:
np.concatenate((a, b.T), axis=1)

array([[ 0., 10.,  0., 20.],
       [20., 30., 10., 30.]])

In [92]:
np.hstack((a, b.T))            # горизонтальное пристекивание

array([[ 0., 10.,  0., 20.],
       [20., 30., 10., 30.]])

In [93]:
np.vstack((a,b))               # вертикальноеи пристекивание

array([[ 0., 10.],
       [20., 30.],
       [ 0., 10.],
       [20., 30.]])

In [95]:
b = a.copy()

In [96]:
np.may_share_memory(a, b)      # может ли содержать обущую память

False

In [97]:
a.sum()

60.0

In [98]:
a.max()

30.0

In [99]:
a = np.random.rand(100000)

In [100]:
%timeit -n 1000 max(a)

8.34 ms ± 205 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [101]:
%timeit -n 1000 a.max()

23.8 µs ± 2.64 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [102]:
a.sum(axis=0)                   # сумма столбцов

50006.694376528416

In [106]:
a = np.array([[1, 2], [3, 4]])
a.prod(axis=1)                  # произведение всех строк  

array([ 2, 12])

In [107]:
a.cumprod()

array([ 1,  2,  6, 24], dtype=int32)

In [109]:
a.mean(axis=0)

array([2., 3.])

In [115]:
a.sort()

In [114]:
a.argsort()                           # отсортировать и вернуть индексы, в котором идут 

array([[0, 1],
       [0, 1]], dtype=int64)

In [116]:
np.diag(a)

array([1, 4])

### Векторизация функции

In [117]:
def heavyside(x):
    if x >= 0:
        return 1
    else:
        return 0

heavyside_vec = np.vectorize(heavyside)
heavyside_vec(np.array([-3, -2, -1, 0, 1, 2, 3]))

array([0, 0, 0, 1, 1, 1, 1])

### Any и All

In [118]:
(a > 10).any()                         # хотя бы кто-то

False

In [119]:
(a < 10).all()                         # все

True

### Загрузка массива в файл

In [121]:
np.save("random.npy", a)

In [122]:
np.load("random.npy")

array([[1, 2],
       [3, 4]])

In [124]:
np.savetxt('random.csv', a, delimiter='\t')

### Задачки

#### Написать функцию, которая поможет развернуть все слова в строке:

In [125]:
def reverser(string):
    return ' '.join(string.split()[::-1])

In [126]:
reverser("a b c")

'c b a'

#### Написать функцию, которая определяет является ли число палиндромом

In [129]:
def is_palindrom(string):
    return string == reverser(string)

In [130]:
is_palindrom("дуд")

True

#### Сложите цифры целого числа

In [132]:
a = 126567654
sum(map(int, list(str(a))))

42

In [134]:
np.array(list(str(a))).astype(int).sum()

42

#### Извлеките из массива числа, делимые на 15.

In [135]:
nums = np.array([45, 55, 60, 37, 100, 105, 220])

mask = nums % 15 == 0

nums[mask]

array([ 45,  60, 105])